spring.application.name=clima
# Porta onde o Servidor gRPC vai ouvir
grpc.server.port=9090

# Configuração do Cliente para se conectar ao próprio servidor
grpc.client.weatherService.address=static://127.0.0.1:9090
grpc.client.weatherService.negotiationType=plaintext